//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tong.ArcFace.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tong.ArcFace.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        internal static string _0 {
            get {
                return ResourceManager.GetString("0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误原因不明 的本地化字符串。
        /// </summary>
        internal static string _1 {
            get {
                return ResourceManager.GetString("1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缓冲下溢 的本地化字符串。
        /// </summary>
        internal static string _10 {
            get {
                return ResourceManager.GetString("10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存贮空间不足 的本地化字符串。
        /// </summary>
        internal static string _11 {
            get {
                return ResourceManager.GetString("11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组件不存在 的本地化字符串。
        /// </summary>
        internal static string _12 {
            get {
                return ResourceManager.GetString("12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全局数据不存在 的本地化字符串。
        /// </summary>
        internal static string _13 {
            get {
                return ResourceManager.GetString("13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的参数 的本地化字符串。
        /// </summary>
        internal static string _2 {
            get {
                return ResourceManager.GetString("2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的AppId 的本地化字符串。
        /// </summary>
        internal static string _28673 {
            get {
                return ResourceManager.GetString("28673", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的SDKkey 的本地化字符串。
        /// </summary>
        internal static string _28674 {
            get {
                return ResourceManager.GetString("28674", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AppId和SDKKey不匹配 的本地化字符串。
        /// </summary>
        internal static string _28675 {
            get {
                return ResourceManager.GetString("28675", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDKKey和使用的SDK不匹配（注意：调用初始化引擎接口时，请确认激活接口传入的参数，并重新激活） 的本地化字符串。
        /// </summary>
        internal static string _28676 {
            get {
                return ResourceManager.GetString("28676", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统版本不被当前SDK所支持 的本地化字符串。
        /// </summary>
        internal static string _28677 {
            get {
                return ResourceManager.GetString("28677", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK有效期过期，需要重新下载更新 的本地化字符串。
        /// </summary>
        internal static string _28678 {
            get {
                return ResourceManager.GetString("28678", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 引擎不支持 的本地化字符串。
        /// </summary>
        internal static string _3 {
            get {
                return ResourceManager.GetString("3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内存不足 的本地化字符串。
        /// </summary>
        internal static string _4 {
            get {
                return ResourceManager.GetString("4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态错误 的本地化字符串。
        /// </summary>
        internal static string _5 {
            get {
                return ResourceManager.GetString("5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户取消相关操作 的本地化字符串。
        /// </summary>
        internal static string _6 {
            get {
                return ResourceManager.GetString("6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作时间过期 的本地化字符串。
        /// </summary>
        internal static string _7 {
            get {
                return ResourceManager.GetString("7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的输入内存 的本地化字符串。
        /// </summary>
        internal static string _73729 {
            get {
                return ResourceManager.GetString("73729", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的输入图像参数 的本地化字符串。
        /// </summary>
        internal static string _73730 {
            get {
                return ResourceManager.GetString("73730", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的脸部信息 的本地化字符串。
        /// </summary>
        internal static string _73731 {
            get {
                return ResourceManager.GetString("73731", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 待比较的两个人脸特征的版本不一致 的本地化字符串。
        /// </summary>
        internal static string _73733 {
            get {
                return ResourceManager.GetString("73733", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户暂停操作 的本地化字符串。
        /// </summary>
        internal static string _8 {
            get {
                return ResourceManager.GetString("8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人脸特征检测错误未知 的本地化字符串。
        /// </summary>
        internal static string _81921 {
            get {
                return ResourceManager.GetString("81921", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人脸特征检测内存错误 的本地化字符串。
        /// </summary>
        internal static string _81922 {
            get {
                return ResourceManager.GetString("81922", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人脸特征检测格式错误 的本地化字符串。
        /// </summary>
        internal static string _81923 {
            get {
                return ResourceManager.GetString("81923", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人脸特征检测参数错误 的本地化字符串。
        /// </summary>
        internal static string _81924 {
            get {
                return ResourceManager.GetString("81924", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人脸特征检测结果置信度低 的本地化字符串。
        /// </summary>
        internal static string _81925 {
            get {
                return ResourceManager.GetString("81925", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Engine不支持的检测属性 的本地化字符串。
        /// </summary>
        internal static string _86017 {
            get {
                return ResourceManager.GetString("86017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需要检测的属性未初始化 的本地化字符串。
        /// </summary>
        internal static string _86018 {
            get {
                return ResourceManager.GetString("86018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 待获取的属性未在process中处理过 的本地化字符串。
        /// </summary>
        internal static string _86019 {
            get {
                return ResourceManager.GetString("86019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PROCESS不支持的检测属性，例如FR，有自己独立的处理函数 的本地化字符串。
        /// </summary>
        internal static string _86020 {
            get {
                return ResourceManager.GetString("86020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的输入图像 的本地化字符串。
        /// </summary>
        internal static string _86021 {
            get {
                return ResourceManager.GetString("86021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的脸部信息 的本地化字符串。
        /// </summary>
        internal static string _86022 {
            get {
                return ResourceManager.GetString("86022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缓冲上溢 的本地化字符串。
        /// </summary>
        internal static string _9 {
            get {
                return ResourceManager.GetString("9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK激活失败，请打开读写权限 的本地化字符串。
        /// </summary>
        internal static string _90113 {
            get {
                return ResourceManager.GetString("90113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK已激活 的本地化字符串。
        /// </summary>
        internal static string _90114 {
            get {
                return ResourceManager.GetString("90114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDK未激活 的本地化字符串。
        /// </summary>
        internal static string _90115 {
            get {
                return ResourceManager.GetString("90115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 detectFaceScaleVal不支持 的本地化字符串。
        /// </summary>
        internal static string _90116 {
            get {
                return ResourceManager.GetString("90116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 激活文件与SDK类型不匹配，请确认使用的sdk 的本地化字符串。
        /// </summary>
        internal static string _90117 {
            get {
                return ResourceManager.GetString("90117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备不匹配 的本地化字符串。
        /// </summary>
        internal static string _90118 {
            get {
                return ResourceManager.GetString("90118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 唯一标识不合法 的本地化字符串。
        /// </summary>
        internal static string _90119 {
            get {
                return ResourceManager.GetString("90119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数为空 的本地化字符串。
        /// </summary>
        internal static string _90120 {
            get {
                return ResourceManager.GetString("90120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本不支持 的本地化字符串。
        /// </summary>
        internal static string _90122 {
            get {
                return ResourceManager.GetString("90122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 签名错误 的本地化字符串。
        /// </summary>
        internal static string _90123 {
            get {
                return ResourceManager.GetString("90123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 激活信息保存异常 的本地化字符串。
        /// </summary>
        internal static string _90124 {
            get {
                return ResourceManager.GetString("90124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 唯一标识符校验失败 的本地化字符串。
        /// </summary>
        internal static string _90125 {
            get {
                return ResourceManager.GetString("90125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 颜色空间不支持 的本地化字符串。
        /// </summary>
        internal static string _90126 {
            get {
                return ResourceManager.GetString("90126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片宽高不支持，宽度需四字节对齐 的本地化字符串。
        /// </summary>
        internal static string _90127 {
            get {
                return ResourceManager.GetString("90127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 激活数据被破坏,请删除激活文件，重新进行激活 的本地化字符串。
        /// </summary>
        internal static string _90129 {
            get {
                return ResourceManager.GetString("90129", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务端未知错误 的本地化字符串。
        /// </summary>
        internal static string _90130 {
            get {
                return ResourceManager.GetString("90130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 激活文件与SDK版本不匹配,请重新激活 的本地化字符串。
        /// </summary>
        internal static string _90132 {
            get {
                return ResourceManager.GetString("90132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备信息太少，不足以生成设备指纹 的本地化字符串。
        /// </summary>
        internal static string _90133 {
            get {
                return ResourceManager.GetString("90133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户端时间与服务器时间（即北京时间）前后相差在30分钟以上 的本地化字符串。
        /// </summary>
        internal static string _90134 {
            get {
                return ResourceManager.GetString("90134", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据校验异常 的本地化字符串。
        /// </summary>
        internal static string _90135 {
            get {
                return ResourceManager.GetString("90135", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传入的AppId和AppKey与使用的SDK版本不一致 的本地化字符串。
        /// </summary>
        internal static string _90136 {
            get {
                return ResourceManager.GetString("90136", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 短时间大量请求会被禁止请求,30分钟之后解封 的本地化字符串。
        /// </summary>
        internal static string _90137 {
            get {
                return ResourceManager.GetString("90137", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 激活文件不存在 的本地化字符串。
        /// </summary>
        internal static string _90138 {
            get {
                return ResourceManager.GetString("90138", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IMAGE模式下不支持全角度(ASF_OP_0_HIGHER_EXT)检测 的本地化字符串。
        /// </summary>
        internal static string _90139 {
            get {
                return ResourceManager.GetString("90139", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法解析主机地址 的本地化字符串。
        /// </summary>
        internal static string _94209 {
            get {
                return ResourceManager.GetString("94209", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法连接服务器 的本地化字符串。
        /// </summary>
        internal static string _94210 {
            get {
                return ResourceManager.GetString("94210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络连接超时 的本地化字符串。
        /// </summary>
        internal static string _94211 {
            get {
                return ResourceManager.GetString("94211", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络未知错误 的本地化字符串。
        /// </summary>
        internal static string _94212 {
            get {
                return ResourceManager.GetString("94212", resourceCulture);
            }
        }
    }
}
